import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useDeletePost } from '@/api/generated/posts/posts'
import { useDeleteComment1 } from '@/api/generated/comments/comments'
import {
  useDeletePost1,
  useDeleteComment,
} from '@/api/generated/moderator/moderator'
import type { ApiResponseUserListItem } from '@/api/generated/model'
import { customInstance } from '@/api/client/axios-client'

// Ban/unban API functions (not yet generated by orval)
const banUser = (id: number, durationHours: number) =>
  customInstance<ApiResponseUserListItem>({
    url: `/api/v1/moderator/users/${id}/ban`,
    method: 'POST',
    params: { durationHours },
  })

const unbanUser = (id: number) =>
  customInstance<ApiResponseUserListItem>({
    url: `/api/v1/moderator/users/${id}/ban`,
    method: 'DELETE',
  })

export function useDeleteOwnPost() {
  const queryClient = useQueryClient()

  return useDeletePost({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['/api/v1/ranking'] })
        queryClient.invalidateQueries({ queryKey: ['/api/v1/posts'] })
      },
    },
  })
}

export function useDeleteOwnComment(postId: number) {
  const queryClient = useQueryClient()

  return useDeleteComment1({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: [`/api/v1/posts/${postId}/comments`] })
      },
    },
  })
}

export function useModDeletePost() {
  const queryClient = useQueryClient()

  return useDeletePost1({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['/api/v1/ranking'] })
        queryClient.invalidateQueries({ queryKey: ['/api/v1/posts'] })
      },
    },
  })
}

export function useModDeleteComment(postId: number) {
  const queryClient = useQueryClient()

  return useDeleteComment({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: [`/api/v1/posts/${postId}/comments`] })
      },
    },
  })
}

export function useBanUser() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ id, durationHours }: { id: number; durationHours: number }) =>
      banUser(id, durationHours),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/v1/admin/users'] })
      queryClient.invalidateQueries({ queryKey: ['/api/v1/moderator/users'] })
    },
  })
}

export function useUnbanUser() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: number) => unbanUser(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/v1/admin/users'] })
      queryClient.invalidateQueries({ queryKey: ['/api/v1/moderator/users'] })
    },
  })
}
